<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5955eb45-17a7-4ce2-9aa0-dd8df113d27e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-menu']/div[2]/ul/li[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3fafcd32-b1b2-4921-a24c-120a79d1dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/youtube-d2a68e9d.svg</value>
      <webElementGuid>8db24ce2-61a6-43d9-bb42-4ec0a5db19c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7118546d-15c6-4aad-b803-64a347139ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-menu&quot;)/div[@class=&quot;icon-sosmed&quot;]/ul[@class=&quot;mb-0&quot;]/li[@class=&quot;c-header__menu-group-list&quot;]/a[1]/img[1]</value>
      <webElementGuid>0be8e644-feb6-48c0-8b99-ae7f8b4aafd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-menu']/div[2]/ul/li[4]/a/img</value>
      <webElementGuid>51f90b81-fa56-4d54-b386-adaccc630406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>efa8a1fe-07dc-4f0b-8343-6c15cb1d54df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/packs/media/svg/youtube-d2a68e9d.svg']</value>
      <webElementGuid>f1b89f2a-2aaa-4e15-9699-1cc913a07118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
