<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e169f15e-20dd-4085-afcb-36ea4f24cd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-menu']/div[2]/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.c-header__menu-group-list > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc668242-5362-42cf-b74c-2ffad247a4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/twitter-ccad8f96.svg</value>
      <webElementGuid>bb1d93b2-1bb4-45f3-8ffd-563d3a92ce92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>97cfd26b-7553-4ad5-8982-85b4b241e70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-menu&quot;)/div[@class=&quot;icon-sosmed&quot;]/ul[@class=&quot;mb-0&quot;]/li[@class=&quot;c-header__menu-group-list&quot;]/a[1]/img[1]</value>
      <webElementGuid>472a6cbf-776d-437e-a1b3-33fd0bb24553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-menu']/div[2]/ul/li/a/img</value>
      <webElementGuid>a4eb9890-0216-4489-b6f5-813adc769f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>70c1b494-6d2f-4368-ace4-2db623c6e56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/packs/media/svg/twitter-ccad8f96.svg']</value>
      <webElementGuid>3ce66f28-1e23-4550-8a55-79eab5362714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
