<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih (1)</name>
   <tag></tag>
   <elementGuidId>29b1f9da-7925-457c-8130-e005d0d19586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2']/div[2]/div[2]/div/div/div[2]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-step2.button-box.no-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a0ad32a-35f8-4c15-a743-909d197506d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-step2 button-box no-active</value>
      <webElementGuid>19f7c670-283c-4e0d-a7b3-48173b8b1f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
            Pilih
           </value>
      <webElementGuid>1d4a7c50-1030-4a9a-9971-d45103b2ee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;c-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 div-text-center&quot;]/div[@class=&quot;c-fa-new-step2&quot;]/div[@class=&quot;row pt-3 row-box pb-5&quot;]/div[@class=&quot;col-sm-12 col-sm-12-step2&quot;]/div[@class=&quot;box-life&quot;]/button[@class=&quot;button-step2 button-box no-active&quot;]</value>
      <webElementGuid>623335ea-f626-4090-8b19-5f0e582e1482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div[2]/div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>cacee35f-90a9-41a8-b7b0-119f61347e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[2]/preceding::button[1]</value>
      <webElementGuid>aff5df25-b819-4b5e-8d49-6e86b8eaeea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih']/parent::*</value>
      <webElementGuid>9c4de311-42ee-4d0e-9696-f9f65cac001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>fc1a0251-2ecd-4d16-bbfb-2ddfead2d5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 
            Pilih
           ' or . = ' 
            Pilih
           ')]</value>
      <webElementGuid>46ce50a5-b441-4aa2-a717-dd1cbb5a5ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
