<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bapak_inlineFormInputGroup</name>
   <tag></tag>
   <elementGuidId>bc99ecd7-6734-446b-b257-d5a872ff9cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineFormInputGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineFormInputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c1c14f7-5d29-4403-a6db-8db3ed1b31b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee168686-b313-4695-8d96-0cf4737e651a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineFormInputGroup</value>
      <webElementGuid>dd9169c3-efd2-4653-9ef1-e50230a096a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama lengkap</value>
      <webElementGuid>692d25ca-7be9-4995-ac8b-05fe1c569771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3 form-control-step-3</value>
      <webElementGuid>15e9659d-47ea-45ff-b629-37a61dcbcd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineFormInputGroup&quot;)</value>
      <webElementGuid>9f543c64-16f8-4356-a34c-24ec478006e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineFormInputGroup']</value>
      <webElementGuid>79bdc029-c19e-4786-b7d9-5185379eeac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>48bf98d0-0b81-4a76-b9c4-61e1870181af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>beb0d623-6caa-4204-9177-75a5bcfc6765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inlineFormInputGroup' and @placeholder = 'Nama lengkap']</value>
      <webElementGuid>0e895fe9-e377-4c61-b286-dceeeca3a459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
