<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih (1)</name>
   <tag></tag>
   <elementGuidId>491697cf-fc63-4bbd-9376-21f46a1b4c46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2']/div[2]/div[2]/div/div/div[2]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-step2.button-box.no-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af638dd3-1b59-415e-9e3e-e218795a4319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-step2 button-box no-active</value>
      <webElementGuid>9deb36f0-a305-4249-ab7a-3d123a62ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
            Pilih
           </value>
      <webElementGuid>a5a294e2-1d68-4006-b5c5-fd970964abf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)/div[@class=&quot;c-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 div-text-center&quot;]/div[@class=&quot;c-fa-new-step2&quot;]/div[@class=&quot;row pt-3 row-box pb-5&quot;]/div[@class=&quot;col-sm-12 col-sm-12-step2&quot;]/div[@class=&quot;box-life&quot;]/button[@class=&quot;button-step2 button-box no-active&quot;]</value>
      <webElementGuid>60ee835a-11af-48a9-b4fe-e38754db0e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2']/div[2]/div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>e2f52c9c-8306-490c-b01f-affa46640c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih'])[2]/preceding::button[1]</value>
      <webElementGuid>00a63757-ec0e-4815-bb6a-ade517057422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih']/parent::*</value>
      <webElementGuid>7adaa4be-61c0-4c85-a453-c17172e6d44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/button</value>
      <webElementGuid>93d6e1a9-1b25-4fa8-87a1-0c3bd82a2788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' 
            Pilih
           ' or . = ' 
            Pilih
           ')]</value>
      <webElementGuid>8df2c8ac-d8b2-4390-946d-792ae27066be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
