<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bapak_inlineFormInputGroup</name>
   <tag></tag>
   <elementGuidId>7872dc6d-a96c-44d7-bd09-a8814cab9c75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineFormInputGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineFormInputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8b5ae42-4312-4fc7-989f-6055f7035215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c33ee020-422a-4f01-9cc6-137e1e71e90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineFormInputGroup</value>
      <webElementGuid>f9326959-58f8-4242-850b-6dd5f24e128e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama lengkap</value>
      <webElementGuid>f67b7383-5988-43a6-b532-ef977a796f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3 form-control-step-3</value>
      <webElementGuid>d264a7a0-0635-4bd4-8945-82d028e2a6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineFormInputGroup&quot;)</value>
      <webElementGuid>8044cc8a-0b51-4533-9b6d-d301fc412424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineFormInputGroup']</value>
      <webElementGuid>89d6d251-bdb5-4199-b0cc-14de4db58f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>ad74d6fd-344f-4943-8cb9-6985d3003db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>63cac39f-2adb-45c7-9a17-09b86cc88f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inlineFormInputGroup' and @placeholder = 'Nama lengkap']</value>
      <webElementGuid>8a18fdd5-e87a-4361-b840-42d3f8fb58a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
