<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>38c2d226-251a-4972-b23a-567462622b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-menu']/div[2]/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>953d168c-5aba-4665-b6c9-6e966170c581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/facebook-3a7931bc.svg</value>
      <webElementGuid>7916f684-844a-45c3-9c27-a2694bea22d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>12944a1e-ceeb-4d07-8509-0dca8185d82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-menu&quot;)/div[@class=&quot;icon-sosmed&quot;]/ul[@class=&quot;mb-0&quot;]/li[@class=&quot;c-header__menu-group-list&quot;]/a[1]/img[1]</value>
      <webElementGuid>d66cf0ed-cf9f-4d79-82f5-3db2bcb8126c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-menu']/div[2]/ul/li[2]/a/img</value>
      <webElementGuid>506e813b-b5e6-45b4-a5cb-cca69cf354ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>ef28592e-ec18-4262-9a64-d3886116aaa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/packs/media/svg/facebook-3a7931bc.svg']</value>
      <webElementGuid>23a5e8c3-6866-47cf-b746-88dfe5e96dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
