<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PILIH2</name>
   <tag></tag>
   <elementGuidId>2821ac23-e386-41ba-bc44-68de1203322f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalCity']/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.buttom-modal.button-continue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e51736e-cf6b-466b-ba00-557f1778e1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttom-modal button-continue</value>
      <webElementGuid>0a6bdd5c-70c6-4015-aead-6478497217d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            PILIH
          </value>
      <webElementGuid>5abdb0e8-8c14-4654-9505-0d6225270af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalCity&quot;)/div[@class=&quot;modal-dialog modal-bottom&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/button[@class=&quot;buttom-modal button-continue&quot;]</value>
      <webElementGuid>de410813-0a0d-40d4-b576-b94d237d098c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalCity']/div/div/div[2]/button</value>
      <webElementGuid>b0158fab-9b9f-442b-883d-5d037e1ed742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA SUBULUSSALAM'])[1]/following::button[1]</value>
      <webElementGuid>f8ec1809-df29-4fa9-927b-4358d53991d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOTA LANGSA'])[1]/following::button[1]</value>
      <webElementGuid>18bb04d2-d9c3-4e49-9b7c-3c51a8ce0165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Provinsi'])[1]/preceding::button[1]</value>
      <webElementGuid>86bf2b1c-3956-4dc6-8cde-650c7f7bc068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACEH'])[2]/preceding::button[1]</value>
      <webElementGuid>f668e152-bd7e-4ba1-a788-07707078fa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PILIH']/parent::*</value>
      <webElementGuid>7213c8d4-0535-429f-8aa4-d7b59831b5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>d1959edc-1f81-4a08-ac85-89c5172bd947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            PILIH
          ' or . = '
            PILIH
          ')]</value>
      <webElementGuid>75ed1645-8f0c-481c-8911-6bd19a48895d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
