<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6e97b440-f5b6-481e-a88c-fac51e8133d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c-menu']/div[2]/ul/li[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5caf47ab-4377-4a6f-8b1e-c7d14978b289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/instagram-4b74d379.svg</value>
      <webElementGuid>e55eec86-8bcb-4c27-97ed-d125ccbcfaa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>645112aa-5909-49ac-8b54-895923bac04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c-menu&quot;)/div[@class=&quot;icon-sosmed&quot;]/ul[@class=&quot;mb-0&quot;]/li[@class=&quot;c-header__menu-group-list&quot;]/a[1]/img[1]</value>
      <webElementGuid>96825865-94b2-438c-a21f-6ef4b04fc591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c-menu']/div[2]/ul/li[3]/a/img</value>
      <webElementGuid>de8bf17e-fad1-4b72-8315-eabbf7221887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/img</value>
      <webElementGuid>3909ecea-10ff-4137-99b2-362fae25665c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/packs/media/svg/instagram-4b74d379.svg']</value>
      <webElementGuid>e2d959d3-8fc6-49bb-b8cb-c05e7a93b4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
