<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bapak_inlineFormInputGroup</name>
   <tag></tag>
   <elementGuidId>11140c7b-b186-4411-b4a7-91dee5763eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineFormInputGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineFormInputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63025b37-8a35-4f85-95f7-d0df8b571e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d0c2252-7b1a-4fef-b6ff-000a75311413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineFormInputGroup</value>
      <webElementGuid>85dcf9a3-2e27-4ebf-82a4-3bc1964a802a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama lengkap</value>
      <webElementGuid>8e0df93d-d143-42e7-8261-bc7ad1dce8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3 form-control-step-3</value>
      <webElementGuid>1f005e8d-9ca8-4b60-bf19-e9823c4afac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineFormInputGroup&quot;)</value>
      <webElementGuid>027a3221-9d62-4a4c-a131-0c26d9c87b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineFormInputGroup']</value>
      <webElementGuid>6155dce1-37af-44ab-9980-d297275658dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>93c64dbd-eb03-4467-9036-71fa9c518ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4f1b611f-fc55-4102-8098-60bd83351d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inlineFormInputGroup' and @placeholder = 'Nama lengkap']</value>
      <webElementGuid>503937ae-1801-4863-b7cb-e842ab6f9283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
