<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ACEH</name>
   <tag></tag>
   <elementGuidId>6b930e55-3401-49a7-95ad-1757bd6028ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalProv']/div/div/div[2]/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.list-group-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1868901d-4941-4d0a-acb1-5bb9588c2206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>9d82421a-4410-489b-8673-0ab25d243625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    ACEH
                   </value>
      <webElementGuid>be33bb61-2839-4d62-9fcb-24973fd4af61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalProv&quot;)/div[@class=&quot;modal-dialog modal-bottom&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ex2&quot;]/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item&quot;]</value>
      <webElementGuid>b3bdbdbf-ad1b-4f8a-9d30-2b1fd1760e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalProv']/div/div/div[2]/div[2]/ul/li</value>
      <webElementGuid>2eb33c2b-81c8-467a-9df9-dfc584338303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Provinsi'])[1]/following::li[1]</value>
      <webElementGuid>e1cfc283-f1f6-4fd8-b640-3f6df59f5a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PILIH'])[1]/following::li[1]</value>
      <webElementGuid>baa48245-015d-4fd6-bc8d-e338e104afe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMATERA UTARA'])[1]/preceding::li[1]</value>
      <webElementGuid>f79ce780-9abe-4927-9863-b35e6a08d52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li</value>
      <webElementGuid>85ac012b-beed-4712-903e-80765aa49260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                    ACEH
                   ' or . = '
                    ACEH
                   ')]</value>
      <webElementGuid>7615e44a-a41e-4876-9bfd-0f7fc19690a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
