<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d99285b4-9c02-4f85-bf98-67e23ba19466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3']/div[2]/div[2]/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;delete&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c40deb1d-b5d0-4e8a-a327-738dfe658dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>1f493d57-a70d-44e1-a7c5-bd7bf899ebef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/ic-caret-down-70786f83.svg</value>
      <webElementGuid>77ec219e-1531-4131-99b3-a03cdf35a4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;c-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 div-text-center&quot;]/div[@class=&quot;c-fa-new-step3 header&quot;]/div[@class=&quot;c-fa-new-step3-content mb-5&quot;]/div[@class=&quot;input-group mt-4&quot;]/div[@class=&quot;input-group-prepend&quot;]/div[@class=&quot;input-group-text&quot;]/img[1]</value>
      <webElementGuid>0de8f4ad-83ec-4db5-8042-f419750fb14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='3']/div[2]/div[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>a00f2f2e-7f7e-4608-8ecf-073fba6e1ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delete']</value>
      <webElementGuid>34ae7b80-b124-4961-a03b-cb3c55d4021e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>14e3d191-cfc7-4245-962c-e1b92f5b531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'delete' and @src = '/packs/media/svg/ic-caret-down-70786f83.svg']</value>
      <webElementGuid>4ebd25da-438e-4f36-a54b-7679bb831043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
