<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3f4d4e45-dbf3-44c1-a485-3a8c548e4e2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']/div[2]/div[2]/div/div/div[2]/div/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;delete&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a235610-6593-4bf1-b3c2-575ffb7dea51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>d9c995f3-6363-4aa1-941b-c4167835a0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/packs/media/svg/ic-caret-down-70786f83.svg</value>
      <webElementGuid>64251459-5cbf-44da-a5be-1c6da3cb71d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;c-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 div-text-center&quot;]/div[@class=&quot;c-fa-new-step3 header&quot;]/div[@class=&quot;fa-new-step1-content mt-3&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-control&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-1 resize-1&quot;]/img[1]</value>
      <webElementGuid>a6444fbb-2fd4-4ea8-8948-1bd84489b817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1']/div[2]/div[2]/div/div/div[2]/div/div/div/div[2]/img</value>
      <webElementGuid>3a6b77fe-54c5-47e3-a15d-bed2ee573cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delete']</value>
      <webElementGuid>f0d3938a-551e-4924-b47e-2bc5e656a43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>9ded504d-cd9f-4c23-8d39-8fd28eb06c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'delete' and @src = '/packs/media/svg/ic-caret-down-70786f83.svg']</value>
      <webElementGuid>40d72663-1db6-4c1e-bca8-5a66407ac55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
