<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hi, bapak test , mohon masukkan nomor_8714e3</name>
   <tag></tag>
   <elementGuidId>9cc349b7-6ff1-4f63-8619-a1bf559184bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineFormInputGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineFormInputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>410d14cd-e132-4cb0-9dff-77f6bddd8038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineFormInputGroup</value>
      <webElementGuid>9a5f47dc-39db-44e1-97d5-5dbafb8feb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>9c051ea1-8fb9-4ffe-8f43-a074999b740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>81xxx xxx xxx</value>
      <webElementGuid>aef9cfba-e9df-49b7-a29d-5559f301113d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3</value>
      <webElementGuid>cab09a39-07ed-40db-b23a-8176779584ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineFormInputGroup&quot;)</value>
      <webElementGuid>edafcf35-b5a9-4123-bb17-3a6ae10e8dc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineFormInputGroup']</value>
      <webElementGuid>0182b4f1-9a29-42c7-af2f-a55433f15a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>d1871c3f-fb0f-4b43-8d86-db4f9ec9d0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2c082347-65f7-483c-9b4c-78a64703586e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inlineFormInputGroup' and @placeholder = '81xxx xxx xxx']</value>
      <webElementGuid>1fb97ee8-6c8a-4041-a7f2-3841468e9efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
