<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hi, bapak Jordan , mohon masukkan nom_5189fa</name>
   <tag></tag>
   <elementGuidId>a429cce2-8716-48fc-b700-8af100105963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineFormInputGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inlineFormInputGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f52b5275-3108-4124-a98b-dc3e3c706334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineFormInputGroup</value>
      <webElementGuid>f9475423-521c-47ea-8efb-20732d81cb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>95b57bf4-15b8-4e1d-afd7-37bccd4e8bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>81xxx xxx xxx</value>
      <webElementGuid>0a319c6c-2705-4e14-a9de-c3a2eea1eb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-3</value>
      <webElementGuid>a7e4fe1c-1bb3-43b1-9f5f-454013608bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineFormInputGroup&quot;)</value>
      <webElementGuid>180caebc-1e2f-40cb-83f1-9e21142cb22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineFormInputGroup']</value>
      <webElementGuid>704d0a12-388d-4cb5-b8a6-6ffb0a28030a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='4']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>520a0d42-7cf4-4175-9ed3-830670886fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bac9523e-221e-494a-aeb6-98b167b69ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inlineFormInputGroup' and @placeholder = '81xxx xxx xxx']</value>
      <webElementGuid>0f60953d-d506-447d-a83e-41f41caac231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
